"""Train the lightweight password model with synthetic labelled examples.

This script intentionally uses only the Python standard library so the project
can run in a basic college lab environment.
"""

from __future__ import annotations

import json
import random
import string
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from password_ai.feature_engineering import extract_features


FEATURES = [
    "length_norm",
    "entropy_norm",
    "unique_ratio",
    "class_ratio",
    "has_lower",
    "has_upper",
    "has_digit",
    "has_symbol",
    "repeat_penalty",
    "run_penalty",
    "sequence_penalty",
    "keyboard_penalty",
    "common_word_penalty",
    "year_penalty",
    "date_penalty",
    "shape_penalty",
    "only_digits_penalty",
    "only_letters_penalty",
    "suffix_digit_penalty",
    "personal_penalty",
]


WORDS = [
    "river",
    "planet",
    "silver",
    "matrix",
    "coffee",
    "garden",
    "school",
    "orange",
    "window",
    "future",
    "signal",
    "rocket",
]

WEAK_BASES = [
    "password",
    "qwerty",
    "welcome",
    "admin",
    "sachin",
    "nishad",
    "college",
    "student",
    "india",
    "cricket",
]


def weak_password() -> str:
    base = random.choice(WEAK_BASES)
    pattern = random.choice(
        [
            base,
            base + random.choice(["123", "1234", "2024", "2025", "007"]),
            base.capitalize() + random.choice(["123", "@123", "2026"]),
            random.choice(["123456", "111111", "abc123", "qwerty123", "987654321"]),
            random.choice(["12/05/2004", "01-01-2000", "2001_05_12"]),
        ]
    )
    return pattern


def medium_password() -> str:
    word = random.choice(WORDS).capitalize()
    glue = random.choice(["@", "#", "_", ""])
    return f"{word}{glue}{random.randint(100, 9999)}"


def strong_password() -> str:
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*_-+="
    if random.random() < 0.45:
        parts = random.sample(WORDS, 4)
        return "-".join(parts) + str(random.randint(10, 99))
    return "".join(random.choice(alphabet) for _ in range(random.randint(14, 22)))


def build_dataset(size: int = 3600) -> list[tuple[dict[str, float], int]]:
    rows: list[tuple[dict[str, float], int]] = []
    for _ in range(size // 3):
        rows.append((extract_features(weak_password()).model, 0))
        rows.append((extract_features(medium_password()).model, 0))
        rows.append((extract_features(strong_password()).model, 1))
    random.shuffle(rows)
    return rows


def sigmoid(value: float) -> float:
    if value < -35:
        return 0.0
    if value > 35:
        return 1.0
    return 1 / (1 + pow(2.718281828, -value))


def train(rows: list[tuple[dict[str, float], int]], epochs: int = 550, rate: float = 0.12) -> tuple[dict[str, float], float]:
    weights = {name: 0.0 for name in FEATURES}
    bias = 0.0
    for _ in range(epochs):
        random.shuffle(rows)
        for features, label in rows:
            score = bias + sum(weights[name] * features.get(name, 0.0) for name in FEATURES)
            prediction = sigmoid(score)
            error = prediction - label
            bias -= rate * error
            for name in FEATURES:
                weights[name] -= rate * error * features.get(name, 0.0)
    return weights, bias


def main() -> None:
    random.seed(42)
    rows = build_dataset()
    weights, bias = train(rows)
    output = {
        "version": "synthetic-logistic-1.0",
        "bias": round(bias, 6),
        "weights": {key: round(value, 6) for key, value in weights.items()},
        "training_note": "Synthetic examples generated by scripts/train_model.py for academic demonstration.",
    }
    output_path = ROOT / "data" / "model.json"
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_text(json.dumps(output, indent=2), encoding="utf-8")
    print(f"Saved model to {output_path}")


if __name__ == "__main__":
    main()
